### ISSUE TITLE
管理服务器 weblogic.security.SecurityInitializationException: Authentication for user weblogic denied

### ISSUE THREAD

**Issue by gaoxinfu** [gaoxinfu/demo-weblogic#1]
详细描述:
```java
[weblogic@localhost base_domain]$ sh startWebLogic.sh 
.
.
JAVA Memory arguments: -Xms512m -Xmx512m
.
WLS Start Mode=Production
.
CLASSPATH=/weblogic/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/weblogic/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/weblogic/jrockit_160_29_D1.2.0-10/lib/tools.jar:/weblogic/wlserver_10.3/server/lib/weblogic_sp.jar:/weblogic/wlserver_10.3/server/lib/weblogic.jar:/weblogic/modules/features/weblogic.server.modules_10.3.6.0.jar:/weblogic/wlserver_10.3/server/lib/webservices.jar:/weblogic/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/weblogic/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/weblogic/wlserver_10.3/common/derby/lib/derbyclient.jar:/weblogic/wlserver_10.3/server/lib/xqrl.jar:.:/usr/local/java/jdk1.8.0_172/lib/dt.jar:/usr/local/java/jdk1.8.0_172/lib/tools.jar
.
PATH=/weblogic/wlserver_10.3/server/bin:/weblogic/modules/org.apache.ant_1.7.1/bin:/weblogic/jrockit_160_29_D1.2.0-10/jre/bin:/weblogic/jrockit_160_29_D1.2.0-10/bin:/usr/local/nodejs/node-v4.4.7-linux-x64/bin:/usr/local/java/jdk1.8.0_172/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/apache-maven-3.0.3/bin:/usr/local/git/bin:/root/bin
.
***************************************************
*  To start WebLogic Server, use a username and   *
*  password assigned to an admin-level user.  For *
*  server administration, use the WebLogic Server *
*  console at http://hostname:port/console        *
***************************************************
starting weblogic with Java version:
java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11)
Oracle JRockit(R) (build R28.2.0-79-146777-1.6.0_29-20111005-1807-linux-ia32, compiled mode)
Starting WLS with line:
/weblogic/jrockit_160_29_D1.2.0-10/bin/java -jrockit   -Xms512m -Xmx512m -Dweblogic.Name=AdminServer -Djava.security.policy=/weblogic/wlserver_10.3/server/lib/weblogic.policy  -Dweblogic.ProductionModeEnabled=true   -da -Dplatform.home=/weblogic/wlserver_10.3 -Dwls.home=/weblogic/wlserver_10.3/server -Dweblogic.home=/weblogic/wlserver_10.3/server   -Dweblogic.management.discover=true  -Dwlw.iterativeDev=false -Dwlw.testConsole=false -Dwlw.logErrorsToConsole=false -Dweblogic.ext.dirs=/weblogic/patch_wls1036/profiles/default/sysext_manifest_classpath:/weblogic/patch_ocp371/profiles/default/sysext_manifest_classpath  weblogic.Server
<Jun 10, 2018 4:02:07 PM PDT> <Info> <Security> <BEA-090905> <Disabling CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true> 
<Jun 10, 2018 4:02:07 PM PDT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG to FIPS186PRNG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true> 
<Jun 10, 2018 4:02:08 PM PDT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Oracle JRockit(R) Version R28.2.0-79-146777-1.6.0_29-20111005-1807-linux-ia32 from Oracle Corporation> 
<Jun 10, 2018 4:02:08 PM PDT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 10.3.6.0  Tue Nov 15 08:52:36 PST 2011 1441050 > 
<Jun 10, 2018 4:02:10 PM PDT> <Info> <Security> <BEA-090065> <Getting boot identity from user.> 
Enter username to boot WebLogic server:weblogic
Enter password to boot WebLogic server:
<Jun 10, 2018 4:02:22 PM PDT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING> 
<Jun 10, 2018 4:02:22 PM PDT> <Info> <WorkManager> <BEA-002900> <Initializing self-tuning thread pool> 
<Jun 10, 2018 4:02:23 PM PDT> <Notice> <Log Management> <BEA-170019> <The server log file /weblogic/user_projects/domains/base_domain/servers/AdminServer/logs/AdminServer.log is opened. All server side log events will be written to this file.> 
<Jun 10, 2018 4:02:27 PM PDT> <Notice> <Security> <BEA-090082> <Security initializing using security realm myrealm.> 
<Jun 10, 2018 4:02:27 PM PDT> <Critical> <Security> <BEA-090403> <Authentication for user weblogic denied> 
<Jun 10, 2018 4:02:27 PM PDT> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: weblogic.security.SecurityInitializationException: Authentication for user weblogic denied
weblogic.security.SecurityInitializationException: Authentication for user weblogic denied
	at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.doBootAuthorization(CommonSecurityServiceManagerDelegateImpl.java:966)
	at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.initialize(CommonSecurityServiceManagerDelegateImpl.java:1054)
	at weblogic.security.service.SecurityServiceManager.initialize(SecurityServiceManager.java:873)
	at weblogic.security.SecurityService.start(SecurityService.java:141)
	at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64)
	Truncated. see log file for complete stacktrace
Caused By: javax.security.auth.login.FailedLoginException: [Security:090304]Authentication Failed: User weblogic javax.security.auth.login.FailedLoginException: [Security:090302]Authentication Failed: User weblogic denied
	at weblogic.security.providers.authentication.LDAPAtnLoginModuleImpl.login(LDAPAtnLoginModuleImpl.java:261)
	at com.bea.common.security.internal.service.LoginModuleWrapper$1.run(LoginModuleWrapper.java:110)
	at com.bea.common.security.internal.service.LoginModuleWrapper.login(LoginModuleWrapper.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	Truncated. see log file for complete stacktrace
> 
<Jun 10, 2018 4:02:27 PM PDT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FAILED> 
<Jun 10, 2018 4:02:27 PM PDT> <Error> <WebLogicServer> <BEA-000383> <A critical service failed. The server will shut itself down> 
<Jun 10, 2018 4:02:27 PM PDT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN> 

```

**Comment by gaoxinfu** [comment]
原因:密码输错了
